version: '3'

services:

  cli:
    image: duyler/php-fpm-zts:latest
    build:
      context: ./
      dockerfile: ./docker/php-cli/Dockerfile
    volumes:
      - .:/var/www
      - ./docker/config/php:/usr/local/etc/php

  php:
    image: duyler/php-fpm-zts:latest
    build:
      context: ./
      dockerfile: ./docker/php-fpm/Dockerfile
    ports:
      - 80:80
    volumes:
    - .:/var/www
    - ./docker/config/php:/usr/local/etc/php
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
